icons_format = "{icon}"

[theme]
theme = "plain"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "tea_timer"
format = " $icon {$minutes:$seconds |}"
done_cmd = "notify-send 'Timer Finished'"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} ^icon_net_down$speed_down.eng(prefix:K) ^icon_net_up$speed_up.eng(prefix:K) via $device" 

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "cpu"
interval = 5
format = " $icon $utilization "
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "memory"
format = " $icon $mem_used.eng(w:4) / $mem_total.eng(w:2)"

[[block]]
block = "backlight"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
format = "$icon $percentage {$time |}"
full_format = "$icon $percentage {$time |}"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
